### ISSUE TITLE
Flickering blocks in the first chunk in debug block states world

### ISSUE THREAD

**Issue by inxomnyaa** [ConcreteMC/Alex#22]
As i finally got to test Alex, i started with opening the block states debug world.

![grafik](https://user-images.githubusercontent.com/8733998/62683722-6cfe2d80-b9bf-11e9-92ed-f12d3e54db70.png)
![grafik](https://user-images.githubusercontent.com/8733998/62683810-a46cda00-b9bf-11e9-9510-4cb52022bfdd.png)

The first chunk seems to constantly load and unload, since the chunk count in the top left switches between 21 and 22

**Comment by kennyvv** [comment]
Fixed in BigRefactor branch
