### ISSUE TITLE
Texture / Model issues

### ISSUE THREAD

**Issue by inxomnyaa** [ConcreteMC/Alex#23]
Some textures and block models behave strangely
Waterlogged = fir leave texture (and green redstone wires):
![grafik](https://user-images.githubusercontent.com/8733998/62683971-f01f8380-b9bf-11e9-97ba-9f3dcd69849c.png)
![grafik](https://user-images.githubusercontent.com/8733998/62684479-0c6ff000-b9c1-11e9-8849-f118f740b7c5.png)

Lava and water textures seem to be animated too fast, and the animation is getting offset by 1px over the time
Seagrass looks very weird
![grafik](https://user-images.githubusercontent.com/8733998/62684119-47255880-b9c0-11e9-85ba-082046ba3f00.png)
Fire is not rendered at all
Wall torch has some serious issues
![grafik](https://user-images.githubusercontent.com/8733998/62684202-7c31ab00-b9c0-11e9-9071-0d58a2a35494.png)
Sapling's transparent part cut out the other layer
![grafik](https://user-images.githubusercontent.com/8733998/62684353-c9ae1800-b9c0-11e9-8007-294ec4e241b9.png)
Vines render the wrong sides, and no backface rendering
![grafik](https://user-images.githubusercontent.com/8733998/62684635-5f49a780-b9c1-11e9-94ca-df585f5b6d09.png)
Brewing stand bottles are too big and rotated
![grafik](https://user-images.githubusercontent.com/8733998/62684730-9c159e80-b9c1-11e9-90bd-180d60d62876.png)
Iron bars 
![grafik](https://user-images.githubusercontent.com/8733998/62684795-bbacc700-b9c1-11e9-8464-02386e33e0be.png)
Tripwire hooks
![grafik](https://user-images.githubusercontent.com/8733998/62684821-c8311f80-b9c1-11e9-9a57-a6d49c03309b.png)
Glass panes only show a dot on top
![grafik](https://user-images.githubusercontent.com/8733998/62684953-075f7080-b9c2-11e9-966e-c07d26cb8c21.png)
Prismarine block/stair animated texture is a stitched static texture
![grafik](https://user-images.githubusercontent.com/8733998/62685064-32e25b00-b9c2-11e9-9bbb-a435ca63423c.png)
Bamboo
![grafik](https://user-images.githubusercontent.com/8733998/62685119-4b527580-b9c2-11e9-9d1d-2b5e0cd8b771.png)
Sea pickle
![grafik](https://user-images.githubusercontent.com/8733998/62685127-51e0ed00-b9c2-11e9-8af5-0ece240784e9.png)
Walls do not render at all
Camp fire and stonecutter stitched animation texture
![grafik](https://user-images.githubusercontent.com/8733998/62685271-a2584a80-b9c2-11e9-864d-8b1ae9792b52.png)
![grafik](https://user-images.githubusercontent.com/8733998/62685383-d895ca00-b9c2-11e9-820b-d0bee7cf9006.png)

Lantern incorrect chain
![grafik](https://user-images.githubusercontent.com/8733998/62685302-b1d79380-b9c2-11e9-8bb6-e23d8c159211.png)
Lectern
![grafik](https://user-images.githubusercontent.com/8733998/62685409-e4818c00-b9c2-11e9-9e9f-545bf8737d62.png)

**Comment by kennyvv** [comment]
Thanks for the report! A lot of these have already been fixed, however haven't been commited yet. I"ll probably commit this tonight

**Comment by kennyvv** [comment]
Many of these have been fixed by PR #24
