### ISSUE TITLE
Unable to fetch Bedrock assets

### ISSUE THREAD

**Issue by Encritary** [ConcreteMC/Alex#32]
Logs:
``
ERROR|MCBedrockAssetUtils|Failed to fetch latest bedrock assets pack.
ERROR|ResourceManager|Could not check for latests assets! Do you have a internet connection up?
``

**Comment by kennyvv** [comment]
A temporary manual fix should work with the latest build of Alex, instructions are available on the wiki here:
https://github.com/kennyvv/Alex/wiki/Bedrock-Assets
