### ISSUE TITLE
Cannot handle a high payload

### ISSUE THREAD

**Issue by jwoff78** [ConcreteMC/Alex#35]
A good example is hypixel is crashed at 

```csharp
if (ShowItemInHand && ItemRenderer != null)
			{
				ItemRenderer.Render(renderArgs);
				
				rendered += ItemRenderer.VertexCount;
			}```

I assume after anti-cheat on that server through a fit.

**Comment by jwoff78** [comment]
idk can't get the code block to work sorry.

**Comment by kennyvv** [comment]
Thanks for the report, however without a stacktrace or log i can't do much with it i'm afraid.

Could you please provide me with these? :)

Also, just a note. I don't recommend playing on a public server, you could get banned or kicked for cheating. As the physics etc don't match up with vanilla as of now.
