### ISSUE TITLE
What about forge?

### ISSUE THREAD

**Issue by Faris90** [ConcreteMC/Alex#36]
Can I add forge mods or any mods on it?

**Comment by TruDan** [comment]
forge is java, alex is dotnet. They do not go very well together :p 

You can write your own plugins for Alex in dotnet. There is an example plugin [Here](https://github.com/kennyvv/Alex/tree/master/src/MiNET.AlexDebug) (old example, not sure if it still works 100%).

**Comment by Faris90** [comment]
how do I build it

**Comment by Faris90** [comment]
ok are you a contributor?

**Comment by kennyvv** [comment]
> forge is java, alex is dotnet. They do not go very well together :p
> 
> You can write your own plugins for Alex in dotnet. There is an example plugin [Here](https://github.com/kennyvv/Alex/tree/master/src/MiNET.AlexDebug) (old example, not sure if it still works 100%).

That is actually a MiNET plugin i used for testing, afraid the Alex plugin system isn't quite ready for usage yet.

Forge mods definitely won't be supported at any point.
