### ISSUE TITLE
Client sets name of language in config (instead of langcode)

### ISSUE THREAD

**Issue by Yexeed** [ConcreteMC/Alex#38]
For a moment, I'm experiencing a couple of bugs. ru-RU language doesn't show up any strings. (required russian font?). And after this, I can't switch to English (United Kingdom) for example. The client sets `"English (United Kingdom)"` in settings config. And on second loading, it fallbacks to system language (maybe). 
I'm on windows and using Windows-DirectX build.
![image](https://user-images.githubusercontent.com/32373441/100462176-e9e47780-30da-11eb-8d93-9ba3d0f0ed9d.png)
![image](https://user-images.githubusercontent.com/32373441/100462184-ec46d180-30da-11eb-9ceb-9a9e5f04fafa.png)
![image](https://user-images.githubusercontent.com/32373441/100462810-dab1f980-30db-11eb-9bed-50744d364c66.png)

**Comment by kennyvv** [comment]
Thanks for the report!

Could you please try setting the language to "en-gb" in your settings file?
Seems like there might be a bug with the language selector!

I'll look into it :smile: 

Thanks for the report :D

**Comment by Yexeed** [comment]
Yes, both "en_gb" and "en_GB" worked if I set it in config file myself
![image](https://user-images.githubusercontent.com/32373441/100463630-329d3000-30dd-11eb-9843-e4acfe6c4029.png)

**Comment by Yexeed** [comment]
But still, if I re-set the language using language selector, client sets value to language name
