### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by borjita2019** [ConcreteMC/Alex#42]
title says all

**Comment by ReinforceZwei** [comment]
Head over to https://github.com/kennyvv/Alex/actions , click on the first item that with a little green tick. (The latest version)
![image](https://user-images.githubusercontent.com/39955851/102693503-0e54ef00-4256-11eb-9e7b-e01bf6b240f8.png)

Scroll down to the bottom and you will see all available downloads. Select one that match your platform and download it.
![image](https://user-images.githubusercontent.com/39955851/102693483-dc438d00-4255-11eb-83f6-df6b2482f295.png)

Unzip the downloaded file and run the binary file. (e.g. `Alex.exe` for Windows)
![image](https://user-images.githubusercontent.com/39955851/102693582-a94dc900-4256-11eb-8ee6-11f0ff92c712.png)

**Comment by kennyvv** [comment]
> Head over to https://github.com/kennyvv/Alex/actions , click on the first item that with a little green tick. (The latest version)
> ![image](https://user-images.githubusercontent.com/39955851/102693503-0e54ef00-4256-11eb-9e7b-e01bf6b240f8.png)
> 
> Scroll down to the bottom and you will see all available downloads. Select one that match your platform and download it.
> ![image](https://user-images.githubusercontent.com/39955851/102693483-dc438d00-4255-11eb-83f6-df6b2482f295.png)
> 
> Unzip the downloaded file and run the binary file. (e.g. `Alex.exe` for Windows)
> ![image](https://user-images.githubusercontent.com/39955851/102693582-a94dc900-4256-11eb-8ee6-11f0ff92c712.png)

Thank you for providing help! I'll be looking into making the installation process a bit easier at some point.

Closing this tho.
