### ISSUE TITLE
Simplify installation/setup process

### ISSUE THREAD

**Issue by kennyvv** [ConcreteMC/Alex#44]
Lately i've been asked quite a lot about how to get Alex running, maybe we should add an auto-updater & github releases?

**Comment by borjita2019** [comment]
yeah, can you add forge java or bedrock addons support?
oh and when i try to link my java account it says Forbidden

**Comment by borjita2019** [comment]
and maybe simplify the installation process, so its more easy and no one asks how to install (like i did)

**Comment by borjita2019** [comment]
sorry for asking this here

**Comment by kennyvv** [comment]
There's now a new github release published everytime i decide to push to github, it's not gonna get any fancier than this from me.
