### ISSUE TITLE
UI & missing translations

### ISSUE THREAD

**Issue by splitice** [ConcreteMC/Alex#50]
![image](https://user-images.githubusercontent.com/468579/106834934-779b9f00-66ea-11eb-9535-0d853c08d181.png)

1. Missing translations on all buttons (latest github actions DirectX build)
2. If UI is left unattended (alt-tabed) it may become unresponsive (all buttons). Background animations continue to work.

**Comment by kennyvv** [comment]
DirectX builds have been discontinued and translation issues have been fixed already.

The unresponsiveness should also be fixed.
