### ISSUE TITLE
Loading stops when trying to load bedrock assets

### ISSUE THREAD

**Issue by shizotoaster** [ConcreteMC/Alex#52]
I've built Alex but it can't load bedrock resources
` INFO|ResourceManager|Imported 17084 blockstates from resourcepack in 6537ms!
 INFO|AtlasGenerator|Generating texture atlas out of 694 bitmaps...
 INFO|AtlasGenerator|TextureAtlas's generated in 5018ms! (86,56MB)
ERROR|Alex|Could not initialize! System.NullReferenceException: Object reference not set to an instance of an object.
   at Alex.Entities.EntityFactory.LoadModels(BedrockResourcePack resourcePack, ResourceManager resources, GraphicsDevice graphics, Boolean replaceModels, IProgressReceiver progressReceiver) in C:\Users\maxim\Desktop\Alex-master\src\Alex\Entities\EntityFactory.cs:line 141`
   
![photo](https://user-images.githubusercontent.com/51480483/112160724-80452780-8bfb-11eb-8181-39b73e22f508.png)
![photo](https://user-images.githubusercontent.com/51480483/112160834-9d79f600-8bfb-11eb-9fec-3e12a3a44ce7.png)

**Comment by kennyvv** [comment]
This issue should be fixed already, closing issue. If the problem still occurs, please let me know.
