### ISSUE TITLE
A few bugs and a feature request

### ISSUE THREAD

**Issue by reisxd** [ConcreteMC/Alex#86]
The bugs:
When selecting default skin(or any skin i couldn't get my skin to get to the menu) the game screen goes entirely black
On the main menu the game lags (might be my pcs fault because its old)
When spamming join server button the gui for the game will load but the main menus gui will still stay

The feature request:
Add offline account support for Java
An option to disable transparent gui

**Comment by kennyvv** [comment]
About the skin selection issue, i will look into that, was already a know issue with that.

If the game lags on the mainmenu, your hardware like you said is most likely too old.

And the join game button should disable itself as soon as you click it, if it isn't doing that,it's a bug. I'll look into it.

I will never support offline/cracked accounts. That would make Alex a cracked client. If you wanna play the game, buy the game. 

Why would i wanna change the transparent UI? It doesn't really impact performance anyways, and i like the way it looks.

**Comment by reisxd** [comment]
> I will never support offline/cracked accounts. That would make Alex a cracked client. If you wanna play the game, buy the game.
Thats fine
> 
> Why would i wanna change the transparent UI? It doesn't really impact performance anyways, and i like the way it looks.

I didn't say change it completely, maybe add an option to disable it for older computers because it lags too much on them:
https://user-images.githubusercontent.com/29177546/129876617-366889c1-fd45-489d-945f-72a5bec564fc.mp4
