### ISSUE TITLE
Model.cs Draw() ParentBone out of range of _matrices

### ISSUE THREAD

**Issue by philipbraatz** [ConcreteMC/Alex#95]
I have no clue why but ParentBone sometimes is a larger index than the _matrices. In this case ParentBone is 18 and _matrices size is 18.
![image](https://user-images.githubusercontent.com/25933765/137750185-de6624a4-5e46-4291-ae68-d42e41a1e867.png)

**Comment by kennyvv** [comment]
Thanks for reporting! Seems to me the indexes don't always get recalculated...

**Comment by kennyvv** [comment]
Closing as i recently refactored some stuff around this and this should be fixed.
